cargo-features = ["strip"]

[workspace]
members  = ["crates/*", "tasks/*"]
resolver = "2"

[workspace.dependencies]
markdown   = "1"
rustc-hash = "2"
serde      = { version = "1" }
swc_core   = { features = ["common", "ecma_ast", "ecma_codegen", "ecma_parser", "ecma_visit"], version = "22" }


[profile.release]
lto           = true
codegen-units = 1
