/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Toc {
  text: string
  id: string
  depth: number
}
export interface Output {
  code: string
  links: Array<string>
  html: string
  title: string
  toc: Array<Toc>
}
/** Turn MDX into JavaScript. */
export function compile(value: string, filepath: string, development: boolean, root: string, defaultLang: string): Promise<Output>
export function compileSync(value: string, filepath: string, development: boolean, root: string, defaultLang: string): Output
