[package]
name    = "mdx_plugin_frontmatter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown   = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
