[package]
name    = "mdx_plugin_normalize_link"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hast     = { path = "../hast" }
markdown = { workspace = true }
