[package]
name    = "mdx_plugin_code_block"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hast     = { path = "../hast" }
swc_core = { workspace = true }
